[build]
builder = "NIXPACKS"
buildCommand = "npm ci --prefix frontend && npm run build --prefix frontend && python3 -m venv /app/.venv && /app/.venv/bin/pip install --upgrade pip && /app/.venv/bin/pip install -e ./backend"

[build.env]
NIXPACKS_TOOLS = "python@3.12 nodejs@20"

[deploy]
startCommand = "/app/.venv/bin/uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}"
